### ISSUE TITLE
Benchmarks with libsodium 1.0.7?

### ISSUE THREAD

**Issue by jedisct1** [dswd/vpncloud.rs#1]
Hi,

And congrats for Vpncloud! 

Could you possibly try running new benchmarks using the current libsodium code (the master branch in Git, which will be tagged 1.0.7 in the next few days)?

Also, on recent Intel CPUs, you may want to use hardware-accelerated AES-GCM instead of ChaCha20-Poly1305. It's likely to be twice as fast.

**Comment by dswd** [comment]
Hi, according to my new benchmarks, libsodium 1.0.7 (current master) brought a small slow-down over libsodium-1.0.3-1-ppa14.04+1 which I had before. The throughput went down from 635 to 595 Mbits. I reran it several times and also verified the old version again: The results seem to be pretty stable (old: 630-640, new: 590-600).

AES-GCM sounds very interesting. If I understand it correctly, it has a 12 byte nonce instead of 8 bytes which means 4 extra bytes per packet. I think this is worth the increased security margin as I am using random initial nonces for all participants. Hardware acceleration and double speed sounds good but it seems that this requires at least libsodium 1.0.4 which afaik has not made it into repositories yet. I will keep an eye on it and plan to include it in future versions. However I have some questions: 
* Do I need to use an additional MAC or does AES-GCM serve as a MAC on its own?
* Does AES-GCM have a separate block counter or does it increment the nonce on its own?

**Comment by jedisct1** [comment]
Thanks for running the benchmark!

The slowdown is quite unexpected, especially as you are using chacha20poly1305.
Glancing at your code, it doesn't seem that you are calling `sodium_init()`.

This is something you must do, before using anything else in the library. If you don't, it will only use the slow, generic implementations, instead of the ones optimized for your current CPU.

AES-GCM has a 12 byte nonce and the output includes a MAC; just like chacha20poly1305, an additional MAC is not required. It also has an internal block counter, so you just need to increment the nonce after each packet no matter what the packet size is.

**Comment by jedisct1** [comment]
Also note that ChaCha20-Poly1305 has a variant with a 12-byte nonce as well (`crypto_aead_chacha20poly1305_ietf_encrypt()`, `crypto_aead_chacha20poly1305_ietf_decrypt()`). But that was also introduced in version 1.0.4.

**Comment by dswd** [comment]
Oops I thought I had that `sodium_init()` in my code. Thanks for pointing that out!

The change had no significant impact on 1.0.3 but with 1.0.7 the new mark is at 770 Mbits, wow.

**Comment by jedisct1** [comment]
Nice! Thanks for the updated results!
